#!/usr/bin/env python
from misc.utility.scons_hints import *
import ctypes
from SCons.Script import *

# Import
Import("env")
Import("env_modules")

# Define Module Activation
env.Append(CPPDEFINES=["JENOVA_CORE_ENABLED"])

# Clone Module Environment
env_jenova = env_modules.Clone()

# Static Linking
jenovaCoreLib = Dir("#modules/jenova_core/library").File("Jenova.Core.Win64.MSVC.jnvlib").abspath
env.Append(LINKFLAGS=[jenovaCoreLib])
env.AppendUnique(LINKFLAGS=["/DEFAULTLIB:wldap32"])
env.AppendUnique(LINKFLAGS=["/DEFAULTLIB:DbgHelp.lib"])